// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY00SmXORLNPOmXpkVJ74L0zGuJ6PYpNo',
    appId: '1:743633605588:web:3b8467a8b2e7209df77c41',
    messagingSenderId: '743633605588',
    projectId: 'multyplay-ef1e9',
    authDomain: 'multyplay-ef1e9.firebaseapp.com',
    storageBucket: 'multyplay-ef1e9.firebasestorage.app',
    measurementId: 'G-PKV1KT44LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABsPY0v_GpguZdC8Xpq_HxZw8SSiCICig',
    appId: '1:743633605588:android:7343b7437f5939f8f77c41',
    messagingSenderId: '743633605588',
    projectId: 'multyplay-ef1e9',
    storageBucket: 'multyplay-ef1e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2jiWaLr80IhnEb6xJkPlNFE_DKUrsTQ',
    appId: '1:743633605588:ios:f76504ac61dd6bbff77c41',
    messagingSenderId: '743633605588',
    projectId: 'multyplay-ef1e9',
    storageBucket: 'multyplay-ef1e9.firebasestorage.app',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL2jiWaLr80IhnEb6xJkPlNFE_DKUrsTQ',
    appId: '1:743633605588:ios:f76504ac61dd6bbff77c41',
    messagingSenderId: '743633605588',
    projectId: 'multyplay-ef1e9',
    storageBucket: 'multyplay-ef1e9.firebasestorage.app',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY00SmXORLNPOmXpkVJ74L0zGuJ6PYpNo',
    appId: '1:743633605588:web:611df476119fe22df77c41',
    messagingSenderId: '743633605588',
    projectId: 'multyplay-ef1e9',
    authDomain: 'multyplay-ef1e9.firebaseapp.com',
    storageBucket: 'multyplay-ef1e9.firebasestorage.app',
    measurementId: 'G-4931HP3RJX',
  );

}