// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2v4FMIXcOJRZKMyNSyPrPJg1k5QbAwWE',
    appId: '1:751780136583:web:35b2bdde4b9fa41d499a22',
    messagingSenderId: '751780136583',
    projectId: 'cardgame-4651a',
    authDomain: 'cardgame-4651a.firebaseapp.com',
    storageBucket: 'cardgame-4651a.firebasestorage.app',
    measurementId: 'G-H03S08V8JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA3HbqPpNJGnRJASp5wbVuamtwY5vcOEM',
    appId: '1:751780136583:android:a40ec14cbf05b7ad499a22',
    messagingSenderId: '751780136583',
    projectId: 'cardgame-4651a',
    storageBucket: 'cardgame-4651a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtJEOaXGRgbeK61iR-6ZXzWlmCsP6wZQ0',
    appId: '1:751780136583:ios:4d42ded524f3984b499a22',
    messagingSenderId: '751780136583',
    projectId: 'cardgame-4651a',
    storageBucket: 'cardgame-4651a.firebasestorage.app',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtJEOaXGRgbeK61iR-6ZXzWlmCsP6wZQ0',
    appId: '1:751780136583:ios:4d42ded524f3984b499a22',
    messagingSenderId: '751780136583',
    projectId: 'cardgame-4651a',
    storageBucket: 'cardgame-4651a.firebasestorage.app',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2v4FMIXcOJRZKMyNSyPrPJg1k5QbAwWE',
    appId: '1:751780136583:web:7a9412f28827da79499a22',
    messagingSenderId: '751780136583',
    projectId: 'cardgame-4651a',
    authDomain: 'cardgame-4651a.firebaseapp.com',
    storageBucket: 'cardgame-4651a.firebasestorage.app',
    measurementId: 'G-2C0TLC4SM5',
  );
}
